name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: echo "Test"

    - name: Build
      run: echo "test2"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Production
      run: echo "Your deployment command goes here"
